exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

title : Spectrum 2
tagline: Spectrum 2 transport
author :
  name : Jan Kaluza
  email : hanzz.k@gmail.com
  github : hanzz
production_url : https://spectrum.im
url: https://spectrum.im
  
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

title: Spectrum 2
description: Spectrum 2 transports
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"