name: Jekyll

on:
  pull_request:
  push:
    branches: master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Bundler
      run: sudo apt install ruby-bundler
    - name: Install dependencies
      run: bundle config set path 'vendor/bundle' && bundle install
    - name: Build
      run: bundle exec jekyll build
