name: Jekyll

on:
  [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Bundler
      run: sudo apt install bundler ruby-nokogiri
    - name: Install dependencies
      run: bundle install --local
    - name: Build
      run: bundle exec jekyll build
